/**
 * Soft magnetic materials.
 *
 * Anchor values (permeability, saturation, one loss point) come from published
 * grade data. Variants are then generated by the relationships that actually
 * govern them:
 *
 * - Lamination thickness: classical eddy-current loss goes with t², so a
 *   thinner gauge of the same grade loses proportionally less at frequency.
 * - Powder-core permeability: a family is one powder pressed to different
 *   distributed gaps. Higher permeability means less gap, so loss per volume
 *   rises and DC-bias capability falls, both roughly with permeability.
 * - Temperature grade: saturation falls as a material approaches its Curie
 *   point; each grade carries its own Curie temperature.
 */

import { KNEE_SHARP, KNEE_SOFT, type CoreMaterial } from "../material-types";

type FerriteRow = [
  id: string,
  name: string,
  mur: number,
  bsat: number,
  alpha: number,
  beta: number,
  refF: number,
  refB: number,
  refPv: number,
  maxFreq: number,
  curie: number,
  tags: string,
];

/** MnZn and NiZn ferrite grades, with one datasheet loss point each. */
const FERRITES: FerriteRow[] = [
  ["n27", "N27", 2000, 0.41, 1.4, 2.7, 25e3, 0.2, 65e3, 150e3, 220, "SMPS 전원 저주파"],
  ["n30", "N30", 4300, 0.38, 1.35, 2.6, 25e3, 0.2, 90e3, 100e3, 130, "광대역 고투자율"],
  ["n41", "N41", 2500, 0.43, 1.4, 2.7, 25e3, 0.2, 60e3, 200e3, 240, "전력 변압기"],
  ["n45", "N45", 5000, 0.39, 1.35, 2.6, 25e3, 0.2, 85e3, 100e3, 150, "광대역"],
  ["n49", "N49", 1500, 0.44, 1.6, 2.6, 500e3, 0.05, 60e3, 3e6, 240, "고주파 500kHz 이상"],
  ["n87", "N87", 2200, 0.39, 1.45, 2.75, 100e3, 0.2, 375e3, 500e3, 210, "SMPS 표준"],
  ["n88", "N88", 2100, 0.4, 1.4, 2.7, 100e3, 0.2, 320e3, 500e3, 220, "저손실 SMPS"],
  ["n92", "N92", 1500, 0.41, 1.5, 2.7, 200e3, 0.1, 95e3, 1e6, 280, "고온 저손실"],
  ["n95", "N95", 3000, 0.41, 1.4, 2.7, 100e3, 0.2, 300e3, 500e3, 215, "고포화 SMPS"],
  ["n97", "N97", 2300, 0.41, 1.42, 2.72, 100e3, 0.2, 290e3, 500e3, 230, "저손실 SMPS"],
  ["3c90", "3C90", 2300, 0.38, 1.46, 2.75, 100e3, 0.2, 400e3, 300e3, 220, "범용 SMPS"],
  ["3c94", "3C94", 2300, 0.38, 1.45, 2.72, 100e3, 0.2, 350e3, 400e3, 220, "SMPS"],
  ["3c95", "3C95", 3000, 0.41, 1.4, 2.7, 100e3, 0.2, 310e3, 500e3, 215, "고포화"],
  ["3c96", "3C96", 2000, 0.42, 1.45, 2.7, 200e3, 0.1, 110e3, 800e3, 240, "고주파 저손실"],
  ["3f3", "3F3", 2000, 0.37, 1.5, 2.7, 200e3, 0.1, 120e3, 700e3, 200, "고주파"],
  ["3f36", "3F36", 1600, 0.36, 1.6, 2.65, 500e3, 0.05, 70e3, 2e6, 220, "초고주파"],
  ["3f4", "3F4", 900, 0.35, 1.75, 2.6, 1e6, 0.03, 90e3, 4e6, 220, "1MHz 이상"],
  ["pc40", "PC40", 2300, 0.39, 1.45, 2.75, 100e3, 0.2, 410e3, 300e3, 215, "범용"],
  ["pc44", "PC44", 2400, 0.39, 1.42, 2.72, 100e3, 0.2, 300e3, 500e3, 215, "저손실"],
  ["pc47", "PC47", 2500, 0.41, 1.4, 2.7, 100e3, 0.2, 250e3, 500e3, 230, "고효율 SMPS"],
  ["pc95", "PC95", 3300, 0.41, 1.38, 2.68, 100e3, 0.2, 280e3, 500e3, 215, "광온도 저손실"],
  ["4f1", "4F1 (NiZn)", 80, 0.32, 1.9, 2.5, 3e6, 0.02, 120e3, 20e6, 260, "NiZn RF 고주파"],
];

type PowderFamily = {
  id: string;
  name: string;
  perms: number[];
  bsat: number;
  density: number;
  /** Loss at 100 kHz / 100 mT for the reference permeability [W/m³]. */
  refPv: number;
  refPerm: number;
  alpha: number;
  beta: number;
  cost: number;
  maxTemp: number;
  color: number;
  note: string;
  tags: string;
};

/**
 * Powder cores are one powder pressed to different distributed gaps. Loss per
 * volume climbs with permeability (less gap doing the work), so each variant's
 * loss is scaled from the family's reference permeability.
 */
const POWDER_FAMILIES: PowderFamily[] = [
  {
    id: "sendust",
    name: "센더스트 (Kool Mµ)",
    perms: [26, 40, 60, 75, 90, 125],
    bsat: 1.05,
    density: 5900,
    refPv: 65e3,
    refPerm: 60,
    alpha: 1.46,
    beta: 2.0,
    cost: 1.3,
    maxTemp: 200,
    color: 0x6b6560,
    note: "분산 공극이라 포화가 완만합니다. DC 바이어스가 큰 인덕터에 유리합니다.",
    tags: "PFC 초크 인덕터 저가",
  },
  {
    id: "mpp",
    name: "MPP (몰리퍼멀로이)",
    perms: [14, 26, 60, 125, 147, 160, 173, 200, 300, 550],
    bsat: 0.75,
    density: 8300,
    refPv: 25e3,
    refPerm: 125,
    alpha: 1.4,
    beta: 2.0,
    cost: 6.0,
    maxTemp: 200,
    color: 0x5e6a72,
    note: "분말 코어 중 손실이 가장 낮지만 가장 비쌉니다.",
    tags: "저손실 필터 공진 고급",
  },
  {
    id: "highflux",
    name: "하이플럭스 (High Flux)",
    perms: [14, 26, 60, 125, 147, 160],
    bsat: 1.5,
    density: 8000,
    refPv: 120e3,
    refPerm: 60,
    alpha: 1.45,
    beta: 2.05,
    cost: 4.0,
    maxTemp: 200,
    color: 0x596570,
    note: "포화 자속밀도가 높아 DC 바이어스에 가장 강합니다.",
    tags: "DC 초크 대전류 스무딩",
  },
  {
    id: "xflux",
    name: "X-Flux (Fe-Si 분말)",
    perms: [26, 40, 60, 90],
    bsat: 1.6,
    density: 7400,
    refPv: 180e3,
    refPerm: 60,
    alpha: 1.5,
    beta: 2.1,
    cost: 1.6,
    maxTemp: 200,
    color: 0x6a5f55,
    note: "높은 포화와 낮은 가격. 손실은 센더스트보다 큽니다.",
    tags: "PFC 부스트 대전류 저가",
  },
  {
    id: "ironpowder",
    name: "철분말 (Iron Powder)",
    perms: [10, 20, 33, 35, 45, 60, 75, 90, 100],
    bsat: 1.38,
    density: 6800,
    refPv: 700e3,
    refPerm: 75,
    alpha: 1.5,
    beta: 2.2,
    cost: 0.15,
    maxTemp: 100,
    color: 0x7a5347,
    note: "가장 싸지만 고주파 손실이 매우 큽니다. 저주파 초크용.",
    tags: "저가 저주파 초크 EMI",
  },
];

type SteelGrade = [
  id: string,
  name: string,
  mur: number,
  bsat: number,
  /** Specific loss [W/kg] at 60 Hz, 1.5 T, for the reference thickness. */
  refLossWkg: number,
  refThickness: number,
  oriented: boolean,
  tags: string,
];

const STEEL_GRADES: SteelGrade[] = [
  ["m15", "M-15", 5000, 1.85, 1.35, 0.35, false, "고효율 변압기 모터"],
  ["m19", "M-19", 4000, 1.8, 1.7, 0.35, false, "범용 변압기 리액터"],
  ["m22", "M-22", 3800, 1.8, 1.85, 0.35, false, "범용"],
  ["m27", "M-27", 3500, 1.79, 2.1, 0.35, false, "모터 고정자"],
  ["m36", "M-36", 3200, 1.78, 2.5, 0.5, false, "저가 모터"],
  ["m43", "M-43", 3000, 1.77, 3.1, 0.5, false, "저가 소형 모터"],
  ["m45", "M-45", 2900, 1.77, 3.4, 0.5, false, "일반 기기"],
  ["m47", "M-47", 2800, 1.76, 3.9, 0.64, false, "저가 대량생산"],
  ["50a470", "50A470", 3300, 1.78, 2.4, 0.5, false, "IEC 무방향성"],
  ["35a300", "35A300", 4200, 1.8, 1.55, 0.35, false, "IEC 고급 무방향성"],
  ["m4", "M4 방향성", 20000, 1.95, 1.0, 0.27, true, "대형 전력 변압기"],
  ["m5", "M5 방향성", 18000, 1.94, 1.15, 0.3, true, "배전 변압기"],
  ["m6", "M6 방향성", 17000, 1.93, 1.3, 0.35, true, "배전 변압기"],
  ["23zdkh", "23ZDKH 고배향", 24000, 1.96, 0.75, 0.23, true, "초저손실 변압기"],
  ["27zh", "27ZH 고배향", 22000, 1.95, 0.85, 0.27, true, "저손실 변압기"],
  ["30zh", "30ZH 고배향", 21000, 1.95, 0.95, 0.3, true, "저손실 변압기"],
];

const STEEL_THICKNESS = [0.18, 0.23, 0.27, 0.3, 0.35, 0.5, 0.64];

type SpecialRow = [
  id: string,
  name: string,
  family: string,
  mur: number,
  bsat: number,
  density: number,
  refF: number,
  refB: number,
  refPv: number,
  maxFreq: number,
  curie: number,
  cost: number,
  knee: number,
  color: number,
  tags: string,
  note: string,
];

const SPECIALS: SpecialRow[] = [
  ["amorphous-2605sa1", "아몰퍼스 2605SA1", "아몰퍼스", 15000, 1.56, 7180, 60, 1.4, 1651, 20e3, 395, 2.0, KNEE_SHARP, 0x6f7a86, "배전 변압기 저손실", "규소강 대비 철손 1/5 수준. 배전용 저손실 변압기에 사용합니다."],
  ["amorphous-2605hb1", "아몰퍼스 2605HB1", "아몰퍼스", 12000, 1.64, 7180, 60, 1.4, 1900, 20e3, 395, 2.2, KNEE_SHARP, 0x6d7884, "고포화 아몰퍼스", "포화가 조금 더 높은 아몰퍼스 등급입니다."],
  ["nanocrystalline-ft3", "나노결정 FT-3M", "나노결정", 30000, 1.23, 7300, 20e3, 0.2, 21900, 200e3, 570, 4.0, KNEE_SHARP, 0x7d8894, "고주파 대전력 CM초크", "높은 투자율과 낮은 손실. 고주파 대전력·노이즈 필터용."],
  ["nanocrystalline-vitroperm", "나노결정 VITROPERM 500F", "나노결정", 60000, 1.2, 7350, 20e3, 0.2, 18000, 200e3, 600, 4.5, KNEE_SHARP, 0x808b97, "커먼모드 초크 고투자율", "투자율이 매우 높아 커먼모드 초크에 널리 쓰입니다."],
  ["permalloy-80", "퍼멀로이 80 (Ni80)", "니켈-철", 80000, 0.75, 8740, 400, 0.5, 900, 50e3, 460, 12, KNEE_SHARP, 0x8f97a0, "계측 저잔류 자기차폐", "투자율이 극히 높지만 포화가 낮고 비쌉니다."],
  ["mumetal", "뮤메탈", "니켈-철", 100000, 0.74, 8700, 400, 0.5, 850, 20e3, 400, 16, KNEE_SHARP, 0x939ba4, "자기차폐 실드", "자기 차폐 전용. 기계적 충격에 투자율이 크게 떨어집니다."],
  ["permalloy-50", "50% 니켈-철", "니켈-철", 40000, 1.5, 8250, 400, 1.0, 2200, 20e3, 480, 9, KNEE_SHARP, 0x8a929b, "고포화 계측 CT", "니켈-철 중 포화가 높아 계기용 변류기에 씁니다."],
  ["hiperco-50", "코발트-철 Hiperco 50", "코발트-철", 10000, 2.35, 8120, 400, 1.5, 6000, 20e3, 940, 40, KNEE_SHARP, 0x9aa2ab, "항공 발전기 고출력밀도", "포화가 가장 높아 출력 밀도가 중요한 항공용에 씁니다."],
  ["vacoflux-17", "코발트-철 Vacoflux 17", "코발트-철", 4000, 2.2, 7950, 400, 1.5, 7000, 20e3, 920, 26, KNEE_SHARP, 0x969ea7, "모터 고포화", "코발트 함량을 낮춰 값을 낮춘 고포화 합금입니다."],
  ["smc-somaloy", "연자성 복합재 SMC", "SMC", 500, 1.6, 7400, 400, 1.0, 25000, 20e3, 500, 2.5, KNEE_SOFT, 0x6d6862, "3D 자속 축방향 모터", "압분 성형이라 3차원 자속 경로를 만들 수 있습니다. 투자율은 낮습니다."],
  ["soft-iron", "연철 (Solid)", "순철", 5000, 2.15, 7870, 60, 1.5, 236000, 200, 770, 0.1, KNEE_SHARP, 0x6e6a66, "솔레노이드 계전기 DC", "적층이 아니라 통쇠라 AC 와전류 손실이 큽니다. DC 솔레노이드·계전기용."],
  ["steel-1010", "연강 1010", "탄소강", 1000, 2.1, 7850, 60, 1.5, 400000, 200, 770, 0.05, KNEE_SHARP, 0x6a6764, "구조 요크 저가", "구조재 겸용. 자기 특성은 나쁘지만 가장 쌉니다."],
  ["stainless-430", "페라이트계 스테인리스 430", "스테인리스", 800, 1.4, 7700, 60, 1.0, 500000, 200, 750, 0.6, KNEE_SHARP, 0x8d949b, "내식 요크 해상", "자성이 있는 스테인리스. 부식 환경의 자로에 씁니다."],
  ["air", "공심 (Air)", "없음", 1, Infinity, 0, 1, 1, 0, 1e9, 1e9, 0, KNEE_SOFT, 0x5a6472, "공심 무포화", "코어 없음. 포화가 없지만 인덕턴스가 매우 작습니다."],
];

const ferriteColor = (mur: number) => (mur > 3000 ? 0x33383f : mur > 1000 ? 0x2f3338 : 0x3a3f45);

function ferriteEntries(): CoreMaterial[] {
  return FERRITES.map(
    ([id, name, mur, bsat, alpha, beta, refF, refB, refPv, maxFreq, curie, tags]) => ({
      id: `ferrite-${id}`,
      name: `페라이트 ${name}`,
      family: "MnZn 페라이트",
      mur,
      bsat,
      density: 4850,
      alpha,
      beta,
      refFreq: refF,
      refB,
      refLoss: refPv,
      knee: KNEE_SHARP,
      maxFreq,
      maxTemp: Math.round(curie * 0.55),
      curie,
      cost: 0.6 + mur / 20000,
      color: ferriteColor(mur),
      tags: ["페라이트", "ferrite", name.toLowerCase(), ...tags.split(" ")],
      provenance: "제조사 등급 데이터 (투자율·포화·손실 1점)",
      note: `${tags.split(" ")[0]} 용도. 큐리 온도 ${curie}°C.`,
    }),
  );
}

function powderEntries(): CoreMaterial[] {
  const out: CoreMaterial[] = [];
  for (const family of POWDER_FAMILIES) {
    for (const perm of family.perms) {
      // Less distributed gap means more of the flux swings in the powder
      // itself, so volumetric loss scales with permeability.
      const lossScale = Math.pow(perm / family.refPerm, 1.15);
      out.push({
        id: `${family.id}-${perm}`,
        name: `${family.name} ${perm}µ`,
        family: family.name,
        mur: perm,
        bsat: family.bsat,
        density: family.density,
        alpha: family.alpha,
        beta: family.beta,
        refFreq: 100e3,
        refB: 0.1,
        refLoss: family.refPv * lossScale,
        knee: KNEE_SOFT,
        maxFreq: perm > 200 ? 200e3 : 1e6,
        maxTemp: family.maxTemp,
        curie: 500,
        cost: family.cost * (1 + perm / 600),
        color: family.color,
        tags: ["분말코어", "powder", family.id, `${perm}u`, ...family.tags.split(" ")],
        provenance: `${family.name} 계열, 기준 ${family.refPerm}µ의 손실을 투자율비 1.15승으로 환산`,
        note: family.note,
      });
    }
  }
  return out;
}

function steelEntries(): CoreMaterial[] {
  const out: CoreMaterial[] = [];
  for (const [id, name, mur, bsat, refLossWkg, refThickness, oriented, tags] of STEEL_GRADES) {
    for (const thickness of STEEL_THICKNESS) {
      // Grain-oriented steel is not rolled thick; skip the combinations that
      // do not exist rather than inventing them.
      if (oriented && thickness > 0.35) continue;
      if (!oriented && thickness < 0.23) continue;
      // Classical eddy-current loss scales with thickness squared.
      const scale = Math.pow(thickness / refThickness, 2);
      const hysteresisShare = 0.55;
      const lossWkg = refLossWkg * (hysteresisShare + (1 - hysteresisShare) * scale);
      out.push({
        id: `steel-${id}-${String(thickness).replace(".", "")}`,
        name: `${oriented ? "" : "규소강판 "}${name} ${thickness}mm`,
        family: oriented ? "방향성 규소강" : "무방향성 규소강",
        mur,
        bsat,
        density: 7650,
        alpha: 1.6,
        beta: 2.0,
        refFreq: 60,
        refB: 1.5,
        refLoss: lossWkg * 7650,
        knee: KNEE_SHARP,
        maxFreq: Math.round(400 * Math.pow(0.35 / thickness, 1.5)),
        maxTemp: 155,
        curie: 745,
        cost: (oriented ? 0.5 : 0.25) * Math.pow(0.35 / thickness, 0.5),
        color: oriented ? 0x9aa3ad : 0x8a9099,
        tags: ["규소강", "steel", "적층", name.toLowerCase(), `${thickness}mm`, ...tags.split(" ")],
        provenance: `${name} 기준 두께 ${refThickness}mm의 비손실을 두께 제곱으로 환산 (와전류 성분만)`,
        note: `${thickness}mm 적층. 60Hz 1.5T에서 ${lossWkg.toFixed(2)} W/kg.`,
      });
    }
  }
  return out;
}

function specialEntries(): CoreMaterial[] {
  return SPECIALS.map(
    ([id, name, family, mur, bsat, density, refF, refB, refPv, maxFreq, curie, cost, knee, color, tags, note]) => ({
      id,
      name,
      family,
      mur,
      bsat,
      density,
      alpha: family === "아몰퍼스" || family === "나노결정" ? 1.5 : 1.6,
      beta: family === "아몰퍼스" ? 1.8 : 2.0,
      refFreq: refF,
      refB,
      refLoss: refPv,
      knee,
      maxFreq,
      maxTemp: Math.min(200, Math.round(curie * 0.4)),
      curie,
      cost,
      color,
      tags: ["특수", ...tags.split(" ")],
      provenance: "재료 등급 공개 데이터",
      note,
    }),
  );
}

export const CORE_MATERIALS: CoreMaterial[] = [
  ...specialEntries(),
  ...ferriteEntries(),
  ...powderEntries(),
  ...steelEntries(),
];
