/**
 * Starting points that already work.
 *
 * A blank parameter sheet is the reason simulators feel hard; every preset
 * here is a real design brief ("5 V 3 A buck inductor") that lands inside its
 * own limits, so the first thing a newcomer sees is a working device.
 */

import type { ParamValues } from "../physics/types";

export interface Preset {
  name: string;
  note: string;
  values: ParamValues;
}

export const PRESETS: Record<string, Preset[]> = {
  inductor: [
    {
      name: "벅 컨버터용 22µH",
      note: "5V 3A · 100kHz · 센더스트 분말 코어",
      values: {
        coreMaterial: "sendust-60",
        conductor: "copper",
        shape: "toroid",
        od: 27,
        id: 14,
        height: 11,
        gap: 0,
        turns: 26,
        awg: 18,
        idc: 3,
        ripple: 30,
        freq: 100e3,
      },
    },
    {
      name: "고주파 공진 인덕터",
      note: "500kHz · 리츠선으로 표피효과 억제",
      values: {
        coreMaterial: "ferrite-n49",
        conductor: "litz",
        shape: "toroid",
        od: 25,
        id: 15,
        height: 10,
        gap: 1.5,
        turns: 18,
        awg: 20,
        idc: 5,
        ripple: 60,
        freq: 500e3,
      },
    },
    {
      name: "60Hz 리액터",
      note: "규소강판 EI · 공극으로 DC 포화 회피",
      values: {
        coreMaterial: "silicon-steel-m19",
        conductor: "copper",
        shape: "ei",
        od: 72,
        id: 32,
        height: 45,
        gap: 3,
        turns: 140,
        awg: 16,
        idc: 6,
        ripple: 10,
        freq: 60,
      },
    },
  ],
  transformer: [
    {
      name: "220V → 24V 100W",
      note: "상용 주파수 EI 적층 변압기",
      values: {
        coreMaterial: "silicon-steel-m19",
        conductor: "copper",
        shape: "ei",
        tongue: 32,
        stack: 38,
        windowWidth: 16,
        windowHeight: 48,
        np: 430,
        ns: 52,
        awgP: 24,
        awgS: 17,
        vin: 220,
        freq: 60,
        pout: 100,
        waveform: "sine",
      },
    },
    {
      name: "SMPS 400V → 12V 300W",
      note: "100kHz 페라이트 · 구형파 구동",
      values: {
        coreMaterial: "ferrite-n87",
        conductor: "litz",
        shape: "ei",
        tongue: 20,
        stack: 20,
        windowWidth: 8,
        windowHeight: 25,
        np: 34,
        ns: 2,
        awgP: 24,
        awgS: 14,
        vin: 400,
        freq: 100e3,
        pout: 300,
        waveform: "square",
      },
    },
    {
      name: "저손실 아몰퍼스 변압기",
      note: "같은 조건에서 철손만 1/5",
      values: {
        coreMaterial: "amorphous-2605sa1",
        conductor: "aluminum",
        shape: "ei",
        tongue: 32,
        stack: 38,
        windowWidth: 16,
        windowHeight: 48,
        np: 520,
        ns: 63,
        awgP: 25,
        awgS: 17,
        vin: 220,
        freq: 60,
        pout: 100,
        waveform: "sine",
      },
    },
  ],
  solenoid: [
    {
      name: "24V 밸브 액추에이터",
      note: "3mm 스트로크 · 연속 통전",
      values: {
        coreMaterial: "soft-iron",
        conductor: "copper",
        plungerDiameter: 12,
        bobbinOd: 30,
        coilLength: 35,
        shell: 4,
        gap: 3,
        turns: 2200,
        awg: 30,
        voltage: 24,
        duty: 100,
      },
    },
    {
      name: "단시간 대출력 펀치",
      note: "듀티 10% · 큰 힘, 짧은 통전",
      values: {
        coreMaterial: "soft-iron",
        conductor: "copper",
        plungerDiameter: 18,
        bobbinOd: 42,
        coilLength: 45,
        shell: 6,
        gap: 6,
        turns: 1200,
        awg: 26,
        voltage: 48,
        duty: 10,
      },
    },
  ],
  motor: [
    {
      name: "24V 소형 산업용",
      note: "네오디뮴 4극 · 1700rpm",
      values: {
        magnet: "ndfeb-n42",
        coreMaterial: "silicon-steel-m19",
        conductor: "copper",
        rotorOd: 40,
        stackLength: 40,
        airGap: 0.5,
        magnetThickness: 5,
        yokeThickness: 10,
        poles: 4,
        slots: 12,
        turnsPerCoil: 30,
        awg: 22,
        voltage: 24,
        loadTorque: 0.15,
        brushDrop: 1.5,
      },
    },
    {
      name: "저가 페라이트 자석형",
      note: "같은 크기, 자속이 약해 토크가 1/3",
      values: {
        magnet: "ferrite-magnet",
        coreMaterial: "silicon-steel-m19",
        conductor: "copper",
        rotorOd: 40,
        stackLength: 40,
        airGap: 0.5,
        magnetThickness: 8,
        yokeThickness: 5,
        poles: 4,
        slots: 12,
        turnsPerCoil: 30,
        awg: 22,
        voltage: 24,
        loadTorque: 0.05,
        brushDrop: 1.5,
      },
    },
    {
      name: "12V 고속 소형",
      note: "턴수를 줄여 회전수를 올린 설계",
      values: {
        magnet: "ndfeb-n42",
        coreMaterial: "silicon-steel-m19",
        conductor: "copper",
        rotorOd: 28,
        stackLength: 25,
        airGap: 0.35,
        magnetThickness: 4,
        yokeThickness: 7,
        poles: 4,
        slots: 9,
        turnsPerCoil: 12,
        awg: 21,
        voltage: 12,
        loadTorque: 0.02,
        brushDrop: 1.5,
      },
    },
  ],
};
